# Performs static code quality analysis using elint and pushes code using Clasp
name: Push Google Apps Script code to script ID - spreadsheet-gas

on:
  # Triggers the workflow on push request events but only for the main branch
  # also only triggers when the push event includes a file in the spreadsheet-gas directory
  push:
    branches: [ main ]
    paths:
      - 'spreadsheet-gas/**'

  workflow_dispatch:

jobs:
  # Static quality analysis test
  pretest:
    runs-on: ubuntu-latest
    name: Pre-test
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - run: |
        cd tests/quality-test/;
        npm install;
        npm run lint || true;
        npm run lint-html || true
    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: eslint-report
        path: tests/quality-test/reports/eslint/
  # Clasp action to push code
  push:
    runs-on: ubuntu-latest
    name: Clasp Push
    needs: pretest
    steps:
      - uses: actions/checkout@v2
      - name: Clasp Action
        uses: jarradprice/clasp-action@v1.0.1
        with:
          accessToken: ${{ secrets.GAS_ACCESS_TOKEN }}
          idToken: ${{ secrets.GAS_ID_TOKEN }}
          refreshToken: ${{ secrets.GAS_REFRESH_TOKEN }}
          clientId: ${{ secrets.GAS_CLIENT_ID }}
          clientSecret: ${{ secrets.GAS_CLIENT_SECRET }}
          scriptId: ${{ secrets.GAS_SCRIPT_ID }}
          rootDir: 'spreadsheet-gas'
          command: 'push'